import * as esbuild from "esbuild";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const isProduction = process.argv.includes("--prod") ||
  process.argv.includes("-p");

const ROOT = path.resolve(__dirname);
const DIST = path.join(ROOT, "dist");

const EXTERNAL_MODULES = [
  "vscode",
  "better-sqlite3",
];

const SHARED_CONFIG = {
  platform: "node",
  target: ["node18"],
  charset: "utf8",
  legalComments: "none",
};

function createExtensionConfig() {
  return {
    ...SHARED_CONFIG,
    entryPoints: [path.join(ROOT, "src", "extension.ts")],
    bundle: true,
    format: "cjs",
    outfile: path.join(DIST, "extension.js"),
    external: EXTERNAL_MODULES,
    logLevel: "info",
    banner: {
      js: "// StoryTree VS Code Extension - Generated by esbuild\n// DO NOT EDIT - This file is auto-generated from src/",
    },
  };
}

function createWebviewConfig() {
  return {
    ...SHARED_CONFIG,
    entryPoints: {
      "webview-bundle": path.join(ROOT, "src", "webview", "index.ts"),
    },
    bundle: true,
    format: "iife",
    outdir: DIST,
    external: [],
    logLevel: "info",
    banner: {
      js: "// StoryTree Webview Bundle - Auto-generated",
    },
  };
}

const devBaseConfig = (base) => ({
  ...base,
  sourcemap: true,
  minify: false,
  define: {
    "process.env.NODE_ENV": '"development"',
    __DEV__: "true",
  },
  metafile: false,
});

const prodBaseConfig = (base) => ({
  ...base,
  sourcemap: false,
  minify: true,
  define: {
    "process.env.NODE_ENV": '"production"',
    __DEV__: "false",
  },
  metafile: true,
  treeShaking: true,
  drop: ["debugger"],
  keepNames: false,
});

async function buildAll(config) {
  const isProd = config.mode === "production";

  const extensionCfg = isProd
    ? prodBaseConfig(createExtensionConfig())
    : devBaseConfig(createExtensionConfig());

  const webviewCfg = isProd
    ? prodBaseConfig(createWebviewConfig())
    : devBaseConfig(createWebviewConfig());

  if (config.watch) {
    console.log("[StoryTree] Starting watch mode...");
    const extCtx = await esbuild.context(extensionCfg);
    await extCtx.watch();

    try {
      const wvCtx = await esbuild.context(webviewCfg);
      await wvCtx.watch();
    } catch {
      console.log("[StoryTree] Webview bundle skipped (no entry point found)");
    }

    console.log("[StoryTree] Watching for changes...");
    return;
  }

  let hasErrors = false;

  try {
    const extResult = await esbuild.build(extensionCfg);
    reportResult("Extension", extResult, isProd);

    if (extResult.errors.length > 0) hasErrors = true;

    try {
      const wvResult = await esbuild.build(webviewCfg);
      reportResult("Webview Bundle", wvResult, isProd);
      if (wvResult.errors.length > 0) hasErrors = true;
    } catch {
      console.log("[StoryTree] Webview bundle skipped (no entry point found)");
    }
  } catch (err) {
    console.error("[StoryTree] Build error:", err);
    process.exit(1);
  }

  if (hasErrors) {
    console.error(`[StoryTree] Build FAILED (${config.mode})`);
    process.exit(1);
  }

  console.log(
    `[StoryTree] ✅ Build successful (${config.mode}) - Output in ${DIST}/`,
  );
}

function reportResult(name, result, isProd) {
  const errors = result.errors.length;
  const warnings = result.warnings.length;

  if (errors > 0) {
    console.error(`  ❌ ${name}: ${errors} error(s)`);
    for (const err of result.errors) {
      console.error(`     ${err.text} (${err.location?.file}:${err.location?.line})`);
    }
  }

  if (warnings > 0) {
    console.warn(`  ⚠️  ${name}: ${warnings} warning(s)`);
  }

  if (errors === 0 && warnings === 0) {
    console.log(`  ✅ ${name}: OK${isProd ? ` (${formatBytes(result.outputSize ?? 0)})` : ""}`);
  }

  if (isProd && result.metafile && !errors) {
    analyzeBundle(name, result.metafile);
  }
}

async function analyzeBundle(name, metafile) {
  try {
    const analysis = await esbuild.analyzeMetafile(metafile, { verbose: false });
    console.log(`\n  📊 ${name} Bundle Analysis:`);
    for (const file of analysis.outputs) {
      if (file.inputs) {
        console.log(`     ${file.path} (${formatBytes(file.bytes)} from ${file.inputs.length} inputs)`);
      }
    }
  } catch {
    // analysis may fail
  }
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

const mode = isProduction
  ? "production"
  : "development";

buildAll({
  mode,
  watch: process.argv.includes("--watch") || process.argv.includes("-w"),
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
